# Generated by Django 4.2.6 on 2023-11-13 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_guide_foranswer_guide_forquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='packageDescription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
